In [1]:
# Python
# numpy
# https://www.w3schools.com/python/numpy_intro.asp

# importar librerIa
import numpy

# definir un array con 5 elementos
array = numpy.array([1, 2, 3, 4, 5])

# imprimir el array
print(array)


[1 2 3 4 5]


In [2]:
import numpy as np

array = np.array([1, 2, 3, 4, 5])

print(array)

[1 2 3 4 5]


In [3]:
import numpy as np

vector = np.array([1, 2, 3, 4, 5])

print(vector)

[1 2 3 4 5]


In [5]:
# versiOn de numpy
import numpy as np

print(np.__version__)

1.18.1


In [6]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

# tipo de dato: numpy.ndarray
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [7]:
import numpy as np

# observe la diferencia con doble parEntesis
arr = np.array((1, 2, 3, 4, 5))

print(arr)

[1 2 3 4 5]


In [8]:
# dimensiones
# 0-D
# 0 dimensiOnes
import numpy as np
arr = np.array(42)
print(arr)

42


In [9]:
# dimensiones
# 1-D
# 1 dimensiOn 
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [10]:
# dimensiones
# 2-D
# 2 dimensiOnes 
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [11]:
# dimensiones
# 3-D
# 3 dimensiOnes
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [12]:
# Mostar el nUmero de Dimensiones de un array

import numpy as np

# 4 arrays
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

# se imprimen sus dimensiones
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [14]:
import numpy as np

# definir un array de 5 dimensiones
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('num. de dimensiones:', arr.ndim)

[[[[[1 2 3 4]]]]]
num. de dimensiones: 5


In [16]:
import numpy as np

arr = np.array([1, 2, 3, 4])

# imprimir el elemento en la posiciOn 0
print(arr[0])

# imprimir el elemento en la posiciOn 3
print(arr[3])

1
4


In [18]:
import numpy as np

arr = np.array([1, 2, 3, 4])

# sumar el elemento de la posiciOn 2  MAS  el elemento de la posiciOn 3
# 3 + 4
print(arr[2] + arr[3])

7


In [22]:
# accediento a elementos de array n-dimensionales
import numpy as np

# array de 2 dimensiones
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2do. elemento del 1ra dimensiOn: ', arr[0, 1])

print('2do. elemento del 2da dimensiOn: ', arr[1, 1])


2do. elemento del 1ra dimensiOn:  2
2do. elemento del 2da dimensiOn:  7


In [27]:
import numpy as np

# array de 2-D
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('5.to elemento de la 2da dimensiOn: ', arr[1, 4])

5.to elemento de la 2da dimensiOn:  10


In [29]:
import numpy as np

# array de 3-D
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr)
print(arr[0, 1, 2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
6


In [30]:
import numpy as np
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('Ultimo elemento de 2-dim: ', arr[1, -1])

Last element from 2nd dim:  10


In [31]:
# Slicing
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])

# solo imprimir de la posiciOn 1 a la posiciOn 5-1
print(arr[1:5])

[2 3 4 5]


In [32]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])

# solo imprimir de la posiciOn 4 a la posiciOn final
print(arr[4:])

[5 6 7]


In [33]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])

# solo imprimir desde el inicio hasta la posiciOn 4-1
print(arr[:4])

[1 2 3 4]


In [34]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])

# solo imprimir desde posiciOn -3, hasta posiciOn -2
print(arr[-3:-1])

[5 6]


In [35]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])

# de posiciOn de 1 a 5-1
# de 2 en 2
print(arr[1:5:2])

[2 4]


In [37]:
import numpy as np
# array de 2-D
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

# el 0 indica la 1ra dim
# el 1:4, se imprime de la posiciOn 1 hasta la posicion 4-1
print(arr[0, 1:4])

[2 3 4]


In [38]:
import numpy as np
# array 2-D
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

# se imprime la columna 2
print(arr[0:2, 2])

[3 8]


In [39]:
import numpy as np
# array 2-D
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


In [40]:
# tipos de datos
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr.dtype)
# enteros

int32


In [41]:
import numpy as np
arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)
# texto o String

<U6


In [42]:
import numpy as np
# crea un array del tipo String
arr = np.array([1, 2, 3, 4], dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [45]:
import numpy as np
arr1 = np.array([1, 2, 3, 4, 5])

# copiar un array
arr2 = arr1.copy()

# arr2 es una copia de arr1

print(arr1)
print(arr2)


[1 2 3 4 5]
[1 2 3 4 5]


In [46]:
# forma de un array
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)


(2, 4)


In [48]:
import numpy as np

# array de 5-dim
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('forma del array :', arr.shape)

[[[[[1 2 3 4]]]]]
forma del array : (1, 1, 1, 1, 4)


In [49]:
# reformar arrays
import numpy as np

# array de 1-dim
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

# se reformatea a un array de 2-dim
newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [50]:
# reformar arrays
import numpy as np

# array de 1-dim
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

# se reformatea a un array de 2-dim
newarr = arr.reshape(3, 4)

print(newarr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [51]:
# reformar arrays
import numpy as np

# array de 1-dim
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

# se reformatea a un array de 2-dim
newarr = arr.reshape(6, 2)

print(newarr)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [52]:
# reformar arrays
import numpy as np

# array de 1-dim
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

# se reformatea a un array de 2-dim
newarr = arr.reshape(2, 6)

print(newarr)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [53]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

# de 1-D a 3-D
newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [54]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [56]:
import numpy as np

# array 2-D
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Aplanamiento a array de 1-D
newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


In [59]:
import numpy as np
# array
arr = np.array([1, 2, 3])

# iteraciOn o RepeticiOn
for x in arr:
  print(x)

1
2
3


In [60]:
import numpy as np
# array
arr = np.array([[1, 2, 3], [4, 5, 6]])

# iteraciOn
for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [61]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


In [62]:
import numpy as np

# array 3-D
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

# iteraciOn
for x in arr:
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [63]:
import numpy as np
# array 3-D
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

# iteraciOn
for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [65]:
import numpy as np
# array 3-D
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
# iteraciOn nditer, permite acceder a los elementos unitarios con 1 solo for
for x in np.nditer(arr):
  print(x)


1
2
3
4
5
6
7
8


In [66]:
# enumerar
import numpy as np

arr = np.array([1, 2, 3])

# idx, index o Indice
# x, variable que representa el valor unitario
for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [67]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [68]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

# concatenar, uniOn de arrays
arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [69]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [70]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=0)

print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [71]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [72]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

# divide en 3 sub-arrays
newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [73]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

# divide en 3 sub-arrays
newarr = np.array_split(arr, 3)

# se lista los 3 sub-arrays
print(newarr[0])
print(newarr[1])
print(newarr[2])


[1 2]
[3 4]
[5 6]


In [74]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

# buscar el elemento de valor 4, devuelve las posiciones donde se ubica tal valor
x = np.where(arr == 4)

print(x)

(array([3, 5, 6], dtype=int64),)


In [75]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

# ubicar donde se cumpla lo sgte. :
x = np.where(arr%2 == 1)

print(x)

(array([0, 2, 4, 6], dtype=int64),)


In [76]:
import numpy as np

arr = np.array([6, 7, 8, 9])

# busca 7 en el array y retorna la posiciOn donde serA insertado
x = np.searchsorted(arr, 7)

print(x)

1


In [79]:
import numpy as np

arr = np.array([1, 3, 5, 7])

# busca las posiciones donde donde serAn insertados los valores
x = np.searchsorted(arr, [2, 4, 6])

print(x)

[1 2 3]


In [80]:
import numpy as np
arr = np.array([3, 2, 0, 1])

# ordenar array de menor a mayor
print(np.sort(arr))

[0 1 2 3]


In [82]:
import numpy as np

arr = np.array(['banana', 'cereza', 'anana'])
# ordenar array de menor a mayor
print(np.sort(arr))

['anana' 'banana' 'cereza']


In [83]:
import numpy as np

arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


In [84]:
import numpy as np

arr = np.array([[3, 2, 4], [5, 0, 1]])

# ordenar array de 2-dim, se ordena en cada dimensiOn
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [85]:
import numpy as np

# array
arr = np.array([41, 42, 43, 44])

# array de filtro
x = [True, False, True, False]

# Filtro, filtra solo los elmentos Verdaderos
newarr = arr[x]

print(newarr)

# True   Verdadero
# False  Falso

[41 43]


In [97]:
from numpy import random

# genea un valor enetero aleatorio
x = random.randint(100)

print(x)

92


In [98]:
from numpy import random

# genea un valor aleatorio
x = random.rand()

print(x)

0.4630017623496723


In [99]:
from numpy import random

# genera 5 nUmeros enteros aleatorios entre 0 y 100-1
x=random.randint(100, size=(5))

print(x)

[63 68 68 38 95]


In [100]:
from numpy import random

# genera 10 nUmeros enteros aleatorios entre 0 y 20-1
x=random.randint(20, size=(10))

print(x)

[ 6 15 13 12 16  0  0 19 15 19]


In [101]:
from numpy import random

# genera 3x5 nUmeros enteros aleatorios entre 0 y 100-1
x = random.randint(100, size=(3, 5))

print(x)

[[14 76  7 72 41]
 [51  1  1 53 90]
 [96 97  2 60  6]]


In [102]:
from numpy import random

x = random.rand(5)

print(x)

[0.15643623 0.14530492 0.22801422 0.16745145 0.30353048]


In [103]:
from numpy import random

x = random.rand(3, 5)

print(x)

[[0.95072715 0.62088242 0.74148792 0.55398915 0.02581546]
 [0.47920441 0.0662394  0.84978757 0.30445119 0.78707568]
 [0.66246611 0.56708949 0.5667352  0.62649525 0.8040004 ]]
